# use in production environment

version: '3.8'

services:
  management_system:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - proceed-ssl:/opt/proceed-ms-server/ssl
      - proceed-ms-server-storage-processes:/opt/proceed-ms-server/Processes
      - proceed-ms-server-storage-databases:/opt/proceed-ms-server/Storage
      - proceed-ms-server-storage-engine:/opt/proceed-ms-server/Engine
      - proceed-ms-server-storage-config:/opt/proceed-ms-server/Config
    container_name: proceed-ms-server
    depends_on:
      - redis
      - opa
    env_file:
      - .env
    ports:
      - 33080:33080
      - 33081:33081
    networks:
      proceed:

  redis:
    image: 'redis:alpine'
    container_name: proceed-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379
    volumes:
      - session_storage:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      proceed:

  opa:
    image: openpolicyagent/opa:0.39.0
    container_name: proceed-opa
    ports:
      - 8181
    command:
      - 'run'
      - '--server'
      - '--config-file=config.yaml'
    volumes:
      - ./config.yaml:/config.yaml
    networks:
      proceed:

volumes:
  session_storage:
    name: session_storage
  proceed-ssl:
    name: proceed-ssl
  proceed-ms-server-storage-processes:
    name: proceed-ms-server-storage-processes
  proceed-ms-server-storage-databases:
    name: proceed-ms-server-storage-databases
  proceed-ms-server-storage-engine:
    name: proceed-ms-server-storage-engine
  proceed-ms-server-storage-config:
    name: proceed-ms-server-storage-config

networks:
  proceed:
    name: proceed
