name: Build, test, and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'
      
      - run: yarn install --frozen-lockfile
      
      # Cache build for this workflow run.
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}
      
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'
          
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}
          
      - run: yarn prettier --check .
