name: Build, test, and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  OUTPUT_PATH_ENGINE_NODE: './build/engine/'
  OUTPUT_PATH_ENGINE_ANDROID: './src/engine/native/android/app/build/outputs/apk/debug/'
  FILE_NAME_NODE_ENGINE: 'PROCEED-Engine-0.1.0.zip'
  FILE_NAME_ANDROID: 'PROCEED-Engine-0.1.0.apk'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      # Cache for this workflow run.
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: cache-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn prettier --check .

  testEngine:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn test-engine --ci

  testEngineE2E:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn test-e2e --ci

  buildEngine:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - lint
      - testEngine
      - testEngineE2E
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn build

      - name: Upload engine build
        uses: actions/upload-artifact@v3
        with:
          name: PROCEED_Engine
          path: ${{ env.OUTPUT_PATH_ENGINE_NODE }}
  #  buildEngineAndroid:
  #    runs-on: ubuntu-latest
  #    if: ${{ github.ref == 'refs/heads/main' }}
  #    needs:
  #      - lint
  #      - testEngine
  #      - testEngineE2E
  # steps:
  #   - uses: actions/cache@v3
  #     timeout-minutes: 2
  #     id: restore-install
  #     with:
  #       path: ./*
  #       key: ${{ github.sha }}-${{ github.run_number }}
  #
  #   - name: Set up Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 16
  #       check-latest: true
  #       cache: 'yarn'
  #
  #   - run: yarn build-android
  #   - run: cp ${{ env.OUTPUT_PATH_ENGINE_ANDROID }}/app-debug.apk ${{ env.BUILD_PATH_ENGINE_ANDROID }}/${{ env.FILE_NAME_ANDROID }}
  #
  #   - name: Upload android engine build
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: PROCEED_Engine_Android
  #       path: ${{ env.OUTPUT_PATH_ENGINE_ANDROID }}/${{ env.FILE_NAME_ANDROID }}

  docker:
    runs-on: ubuntu-latest
    needs: buildEngine
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Download engine build
        uses: actions/download-artifact@v3
        with:
          name: PROCEED_Engine
          path: build/engine

      - name: Display structure of downloaded files
        run: ls build/engine

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: proceed/engine
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ./build/engine/
          tag: edge

  deployEngineStaging:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      # Get the new version from dockerhub
      - run: ssh staging "sudo docker run --rm -e MS_TAG="edge" -e ENGINE_TAG="edge" -v /var/run/docker.sock:/var/run/docker.sock -v "\$PWD:\$PWD" -w="\$PWD" docker/compose:1.29.0 pull engine"

      # Restart the engine container with the new image
      - run: ssh staging "sudo docker run --rm -e MS_BIND_MOUNT_DIRECTORY="/var/PROCEED/ms-server" -e ENGINE_BIND_MOUNT_DIRECTORY="/var/PROCEED/engine" -e MS_LOG_DRIVER="local" -e ENGINE_LOG_DRIVER="local" -e MS_HTTPS_PORT="443" -e MS_TAG="edge" -e ENGINE_TAG="edge" -v /var/run/docker.sock:/var/run/docker.sock -v "\$PWD:\$PWD" -w="\$PWD" docker/compose:1.29.0 up -d --remove-orphans engine"

      # Remove unused images
      - run: ssh staging "sudo docker image prune -f -a"
