name: Build, test, and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  OUTPUT_PATH_ENGINE_NODE: './build/engine/'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      # Cache for this workflow run.
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: cache-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn prettier --check .

  test-engine:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn test-engine --ci

  testEngineE2E:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn test-e2e --ci

  buildEngine:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - run: yarn build

      - name: Upload engine build
        uses: actions/upload-artifact@v3
        with:
          name: PROCEED_Engine
          path: ${{ env.OUTPUT_PATH_ENGINE_NODE }}
