name: Build, test, and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  OUTPUT_PATH_ENGINE_NODE: './build/engine/'
  OUTPUT_PATH_ENGINE_ANDROID: './src/engine/native/android/app/build/outputs/apk/debug/'
  OUTPUT_PATH_MS_SERVER: './build/management-system/server/'
  FILE_NAME_NODE_ENGINE: 'PROCEED-Engine-0.1.0.zip'
  FILE_NAME_ANDROID: 'PROCEED-Engine-0.1.0.apk'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      # Cache for this workflow run.
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: cache-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn prettier --check .

  testEngine:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn test-engine --ci

  testEngineE2E:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn test-e2e --ci

  testMS:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn test-ms --ci

  buildEngine:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - lint
      - testEngine
      - testEngineE2E
      - testMS
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn build

      - name: Upload engine build
        uses: actions/upload-artifact@v3
        with:
          name: PROCEED_Engine
          path: ${{ env.OUTPUT_PATH_ENGINE_NODE }}
  #  buildEngineAndroid:
  #    runs-on: ubuntu-latest
  #    if: ${{ github.ref == 'refs/heads/main' }}
  #    needs:
  #      - lint
  #      - testEngine
  #      - testEngineE2E
  # steps:
  #   - uses: actions/cache@v3
  #     timeout-minutes: 2
  #     id: restore-install
  #     with:
  #       path: ./*
  #       key: ${{ github.sha }}-${{ github.run_number }}
  #
  #   - name: Set up Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 16
  #       check-latest: true
  #       cache: 'yarn'
  #
  #   - run: yarn build-android
  #   - run: cp ${{ env.OUTPUT_PATH_ENGINE_ANDROID }}/app-debug.apk ${{ env.BUILD_PATH_ENGINE_ANDROID }}/${{ env.FILE_NAME_ANDROID }}
  #
  #   - name: Upload android engine build
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: PROCEED_Engine_Android
  #       path: ${{ env.OUTPUT_PATH_ENGINE_ANDROID }}/${{ env.FILE_NAME_ANDROID }}

  buildMS:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - lint
      - testEngine
      - testEngineE2E
      - testMS
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: yarn build-ms-server

      - name: Upload MS server build
        uses: actions/upload-artifact@v3
        with:
          name: PROCEED_Management_System_Server
          path: ${{ env.OUTPUT_PATH_MS_SERVER }}

  dockerStaging:
    runs-on: ubuntu-latest
    needs:
      - buildEngine
      - buildMS
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}
      # TODO: Use matrix for engine and ms docker
      - name: Download engine build
        uses: actions/download-artifact@v3
        with:
          name: PROCEED_Engine
          path: ${{ env.OUTPUT_PATH_ENGINE_NODE }}

      - name: Display structure of downloaded files
        run: ${{ env.OUTPUT_PATH_ENGINE_NODE }}

      - name: Kaniko build engine
        uses: aevea/action-kaniko@master
        with:
          image: proceed/engine
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ${{ env.OUTPUT_PATH_ENGINE_NODE }}
          tag: edge

      - name: Download MS server build
        uses: actions/download-artifact@v3
        with:
          name: PROCEED_Management_System_Server
          path: ${{ env.OUTPUT_PATH_MS_SERVER }}

      - name: Display structure of downloaded files
        run: ${{ env.OUTPUT_PATH_MS_SERVER }}

      - name: Kaniko build MS server
        uses: aevea/action-kaniko@master
        with:
          image: proceed/ms-server
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ${{ env.OUTPUT_PATH_MS_SERVER }}
          tag: edge

  dockerProduction:
    runs-on: ubuntu-latest
    needs:
      - buildEngine
      - buildMS
    if: false
    steps:
      - uses: actions/cache@v3
        timeout-minutes: 2
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Download engine build
        uses: actions/download-artifact@v3
        with:
          name: PROCEED_Engine
          path: ${{ env.OUTPUT_PATH_ENGINE_NODE }}

      - name: Display structure of downloaded files
        run: ${{ env.OUTPUT_PATH_ENGINE_NODE }}

      - name: Kaniko build engine
        uses: aevea/action-kaniko@master
        with:
          image: proceed/engine
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ${{ env.OUTPUT_PATH_ENGINE_NODE }}
          tag: latest

      - name: Download MS server build
        uses: actions/download-artifact@v3
        with:
          name: PROCEED_Management_System_Server
          path: ${{ env.OUTPUT_PATH_MS_SERVER }}

      - name: Display structure of downloaded files
        run: ${{ env.OUTPUT_PATH_MS_SERVER }}

      - name: Kaniko build MS server
        uses: aevea/action-kaniko@master
        with:
          image: proceed/ms-server
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ${{ env.OUTPUT_PATH_MS_SERVER }}
          tag: latest

  deployEngineStaging:
    needs: dockerStaging
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: Staging
      ENGINE_TAG: edge
      MS_TAG: edge
      LOG_DRIVER: local
    secrets:
      SSH_USER: ${{ secrets.STAGING_SSH_USER }}
      SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
      SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

  deployEngineProduction:
    needs: dockerProduction
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: Production
      ENGINE_TAG: latest
      MS_TAG: latest
      LOG_DRIVER: gcplogs
    secrets:
      SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
      SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
      SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
