name: Build, test, and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'
      
      - run: yarn install --frozen-lockfile
      
      - run: yarn test
      
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: yarn prettier --check .
