name: Deploy to an environment

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      ENGINE_TAG:
        required: true
        type: string
      MS_TAG:
        required: true
        type: string
      LOG_DRIVER:
        required: true
        type: string
    secrets:
      SSH_USER:
        required: true
      SSH_KEY:
        required: true
      SSH_HOST:
        required: true

env:
  ENV: ${{ inputs.ENVIRONMENT }}
  ENGINE_TAG: ${{ inputs.ENGINE_TAG }}
  MS_TAG: ${{ inputs.MS_TAG }}
  LOG_DRIVER: ${{ inputs.LOG_DRIVER }}

jobs:
  deployEngine:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/$ENV.key
          chmod 600 ~/.ssh/$ENV.key
          cat >>~/.ssh/config <<END
          Host $ENV
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/$ENV.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - run: echo "$LOG_DRIVER"

      # Get the new version from dockerhub
      - run: ssh $ENV "sudo docker run --rm -e MS_TAG="$MS_TAG" -e ENGINE_TAG="$ENGINE_TAG" -v /var/run/docker.sock:/var/run/docker.sock -v "\$PWD:\$PWD" -w="\$PWD" docker/compose:1.29.0 pull engine"

      # Restart the engine container with the new image
      - run: ssh $ENV "sudo docker run --rm -e MS_BIND_MOUNT_DIRECTORY="/var/PROCEED/ms-server" -e ENGINE_BIND_MOUNT_DIRECTORY="/var/PROCEED/engine" -e MS_LOG_DRIVER="${{ vars.LOG_DRIVER }}" -e ENGINE_LOG_DRIVER="${{ vars.LOG_DRIVER }}" -e MS_HTTPS_PORT="443" -e MS_TAG="$MS_TAG" -e ENGINE_TAG="$ENGINE_TAG" -v /var/run/docker.sock:/var/run/docker.sock -v "\$PWD:\$PWD" -w="\$PWD" docker/compose:1.29.0 up -d --remove-orphans engine"

      # Remove unused images
      - run: ssh $ENV "sudo docker image prune -f -a"
